### ISSUE TITLE
Confirm fromBlock defaults

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#142]
The block numbers from which indexing begins should be the block numbers where Pangolin & Uniswap started operating (if not before). Currently, these block numbers default to the following values in `exrproxy-env/autobuild/xquery*.yaml`:

```
      chains:
        - name: AVAX_PANGOLIN
          - name: Pangolin_Router
[...]
          historical:
          - fromBlock: "6800000"
        - name: ETH_UNISWAP
[...]
          historical:
          - fromBlock: "13600000"
```
We need to investigate and either confirm or adjust both those `fromBlock` numbers (for Pangolin and for Uniswap).
