### ISSUE TITLE
builder.py generates duplicate entries

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#172]
`builder.py` generates duplicate entries in `docker-compose.yml` for each of the following xquery event processor containers:
```
####avax_pangolin_approval STACK START
####avax_pangolin_burn STACK START
####avax_pangolin_mint STACK START
####avax_pangolin_swap STACK START
####avax_pangolin_sync STACK START
####avax_pangolin_transfer STACK START
####eth_uniswap_v2_approval STACK START
####eth_uniswap_v2_burn STACK START
####eth_uniswap_v2_mint STACK START
####eth_uniswap_v2_swap STACK START
####eth_uniswap_v2_sync STACK START
####eth_uniswap_v2_transfer STACK START
####eth_uniswap_v3_approval STACK START
####eth_uniswap_v3_burn STACK START
####eth_uniswap_v3_mint STACK START
####eth_uniswap_v3_swap STACK START
####eth_uniswap_v3_sync STACK START
####eth_uniswap_v3_transfer STACK START
```
For example, the following exact entry is found twice in `docker-compose.yml`:
```
####avax_pangolin_approval STACK START
  xquery-event-processor-avax-pangolin-approval:
    image: blocknetdx/xquery-event-processor:latest
    depends_on:
      - "xquery-graphql-engine"
      - "xquery-gateway-processor"
      - "xquery-db-processor"
    restart: always
    environment:
      NAME: AVAX_PANGOLIN
      EVENT_TYPE: Approval
      WORKER_THREADS: 30
      CHAIN_HOST: http://172.31.11.28:9650/ext/bc/C/rpc
      DB_HOST: 172.31.14.176
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespassword
      DB_DATABASE: postgres
      ZMQ_GATEWAY_HOST: 172.31.13.138
      ZMQ_GATEWAY_PORT1: 5555
      ZMQ_GATEWAY_PORT2: 5556
    volumes:
      - ${PWD}/abi/pangolinRouter.json:/app/manager/abi.json
      - ${PWD}/xquery.yaml:/app/manager/query.yaml
      - ${PWD}/scalene_profiles:/app/manager/profile
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    networks:
      backend:
        ipv4_address: 172.31.6.112
####avax_pangolin_approval STACK END
```
