### ISSUE TITLE
Expose port 41412 on snode container

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#28]
The snode mainnet P2P port (41412) needs to be exposed so the snode daemon can receive requests on the P2P mainnet.

`app.py` currently generates a `dockercompose-custom.yaml` file with an `snode` entry like this:

```
snode:
    image: blocknetdx/servicenode:latest
    entrypoint: /opt/blockchain/start-snode.sh
    restart: unless-stopped
    environment:
```

It should generate an `snode` entry like this:
```
  snode:
    image: blocknetdx/servicenode:latest
    entrypoint: /opt/blockchain/start-snode.sh
    restart: unless-stopped
    expose:
      - 41412
    ports:
      - "41412:41412"
    environment:
```

**To Do:**

- [ ] Expose port 41412 on the snode container as described above.
