### ISSUE TITLE
Adjust exposure of port 41412 on snode container

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/exrproxy-env#30]
Sorry, we made a slight mistake in describing how port 41412 should be exposed on the snode container.

app.py currently generates a dockercompose-custom.yaml file with an snode entry like this:

```
  snode:
    image: blocknetdx/servicenode:latest
    entrypoint: /opt/blockchain/start-snode.sh
    restart: unless-stopped
    expose:
      - 41412
    ports:
      - "41412:41412"
    environment:
```
It should generate an snode entry like this:

```
  snode:
    image: blocknetdx/servicenode:latest
    entrypoint: /opt/blockchain/start-snode.sh
    restart: unless-stopped
    ports:
      - "41412:41412"
    environment:
```
To Do:

- [ ] Adjust exposure of port 41412 on the snode container as described above.
