### ISSUE TITLE
autodeploy XQuery stack from custom.yaml

### ISSUE THREAD

**Issue by pom11** [blocknetdx/exrproxy-env#69]
Add XQuery graph in `custom.yaml` in `daemons` something like:
```yaml
- j2template: dockercompose.j2
  name: dockercompose
  daemons:
    - name: XQUERY
      graph: AVAX
      endpoint: /xquery
      chains:
        - name: AVAX
          abi: avax.json
          query:
          - name: Swap
```
