### ISSUE TITLE
add external support for AVAX on XQuery 

### ISSUE THREAD

**Issue by pom11** [blocknetdx/exrproxy-env#71]
make autobuild capable to point XQuery stack to external hosts like 

```yaml
graph: AVAX
endpoint: /xquery
chains:
  - name: AVAX
    rpc_host: EXTERNAL_HOST_HERE
    abi: avax.json
    query:
    - name: Swap
    address:
    - name: Pangolin_Router
      address: '0xE54Ca86531e17Ef3616d22Ca28b0D458b6C89106'
    historical:
    - fromBlock: "6800000"
   ```
